name: Generate PDF from Markdown

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Output Folder
        run: mkdir -p final_pdfs

      - name: Run Pandoc PDF Converter
        run: |
          for file in *.md; do
            [ -e "$file" ] || continue
            
            # 👈 This line checks if the file name is readme.md or README.md and skips it
            if [ "${file,,}" = "readme.md" ]; then
              echo "Skipping $file..."
              continue
            fi
            
            filename="${file%.md}"
            echo "Converting $file to final_pdfs/${filename}.pdf..."
            docker run --rm -v ${{ github.workspace }}:/data pandoc/latex:latest --output="final_pdfs/${filename}.pdf" "$file"
          done

      - name: Commit and Push PDFs Directly to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          
          git add final_pdfs/*.pdf
          git commit -m "Automated PDF update [skip ci]" || echo "No changes to commit"
          git push
